### ISSUE TITLE
error running

### ISSUE THREAD

**Issue by carlostkd** [yanofsky/dump1090-stream-parser#2]
HI , that program is was it was looking a long time ago for.
unfortunatly something is wrong perhaps with my system because when i run the command to start loggin in i receive this error message:

 Traceback (most recent call last):
  File "dump1090-stream-parser.py", line 214, in <module>
    main()
  File "dump1090-stream-parser.py", line 41, in main
    conn = sqlite3.connect(args.database)
sqlite3.OperationalError: unable to open database file

any help are welcome.
thanks in advanced

**Comment by yanofsky** [comment]
What command did you use to try to start the program? Did you use any options?

**Comment by carlostkd** [comment]
i have started the program with this command:

python dump1090-stream-parser.py -l (my rpi ip)  -d adsblog.db --batch-size 20

**Comment by yanofsky** [comment]
Do you get the error if you run this?
python dump1090-stream-parser.py -l (my rpi ip) --batch-size 20

**Comment by carlostkd** [comment]
i get this:

python dump1090-stream-parser.py -l 192.168.192.3 --batch-size 20
Traceback (most recent call last):
  File "dump1090-stream-parser.py", line 214, in <module>
    main()
  File "dump1090-stream-parser.py", line 41, in main
    conn = sqlite3.connect(args.database)
sqlite3.OperationalError: unable to open database file

**Comment by yanofsky** [comment]
are you sure that however you're running the script has proper permissions to open adsblog.db

**Comment by carlostkd** [comment]
:) :) :) why we need root for that? yeahhh yet works fine :) thank you


 sudo python dump1090-stream-parser.py -l 192.168.192.3 --batch-size 20
Connected to dump1090 broadcast
averging 51.0842634926 rows per second
averging 65.381698355 rows per second
averging 72.5540225159 rows per second
averging 69.1058736537 rows per second
averging 64.867122942 rows per second
averging 70.5955024782 rows per second
averging 67.1325344881 rows per second
averging 66.3826319801 rows per second
averging 59.4912703171 rows per second
averging 65.1423996571 rows per second
averging 68.1609614909 rows per second
averging 70.5618783572 rows per second
averging 60.9386378386 rows per second
averging 63.8675642188 rows per second
averging 59.0013432639 rows per second
averging 56.243661603 rows per second

**Comment by yanofsky** [comment]
huh, not sure why you need to be root, but glad you got it up and running
